# Generated by Django 4.1.7 on 2023-05-22 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('acheve', models.CharField(choices=[('o', 'Oui'), ('n', 'Non')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('fichier_CV', models.FileField(upload_to='personnel/cv/')),
                ('fichier_photo', models.ImageField(upload_to='personnel/photos/')),
                ('lien_linkedIn', models.URLField(blank=True)),
                ('equipeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.equipe')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='projetID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.projet'),
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='details/')),
                ('projetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.projet')),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.service')),
            ],
        ),
    ]
