# Generated by Django 4.1.7 on 2023-05-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_projet_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='userID',
        ),
    ]
