# Generated by Django 4.1.7 on 2023-05-24 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_projet_userid'),
    ]

    operations = [
    ]
